# Generated by Django 2.0.5 on 2018-06-13 13:37

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Název')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menu',
            },
        ),
        migrations.CreateModel(
            name='GalleryPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Název obrázku')),
                ('img', models.ImageField(upload_to='', verbose_name='Obrázek')),
            ],
            options={
                'verbose_name': 'Obrázek v galerii',
                'verbose_name_plural': 'Obrázky v galerii',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=200, verbose_name='Text v menu')),
                ('item_external', models.CharField(blank=True, help_text='Použijte při odkazování mimo stránky školy.', max_length=500000, null=True, verbose_name='vnější stránka (odkaz)')),
                ('item_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('item_link', models.CharField(editable=False, max_length=500000)),
                ('item_category', adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zsbila.Category')),
            ],
            options={
                'verbose_name': 'položka v menu',
                'verbose_name_plural': 'položky v menu',
                'ordering': ['item_order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200, verbose_name='Nadpis')),
            ],
            options={
                'verbose_name': 'statická stránka',
                'verbose_name_plural': 'statické stránky',
            },
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200, verbose_name='Nadpis Bloku')),
                ('block_type', models.CharField(choices=[('TEXT', 'textový'), ('PIC', 'obrázkový'), ('ALT', 'střídavý'), ('LIST', 'seznam')], max_length=9, verbose_name='Typ bloku')),
                ('block_text', models.TextField(verbose_name='Text')),
                ('block_image', models.ImageField(upload_to='', verbose_name='Obrázek')),
                ('block_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('block_page', adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zsbila.Page')),
            ],
            options={
                'verbose_name': 'blok',
                'verbose_name_plural': 'bloky',
                'ordering': ['block_order'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_pinned', models.BooleanField(verbose_name='Připnutý na vrchu')),
                ('title_text', models.CharField(max_length=200, verbose_name='Nadpis')),
                ('post_text', models.TextField(verbose_name='Text')),
                ('post_short_text', models.TextField(editable=False)),
                ('post_long_text', models.TextField(editable=False)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('publisher', models.CharField(blank=True, editable=False, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'příspěvek',
                'verbose_name_plural': 'příspěvky',
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='item_internal',
            field=models.ForeignKey(blank=True, help_text='Použijte při odkazování na stránku školy.', null=True, on_delete=django.db.models.deletion.CASCADE, to='zsbila.Page', verbose_name='vnitřní stránka'),
        ),
    ]
