# Generated by Django 2.1.3 on 2018-11-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zsbila', '0002_auto_20181121_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kontakty',
            old_name='nazev',
            new_name='jmeno',
        ),
    ]
