# Generated by Django 2.1.3 on 2018-11-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zsbila', '0003_auto_20181121_1512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kontakty',
            new_name='Contact',
        ),
    ]
