# Generated by Django 2.1.3 on 2018-12-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zsbila', '0005_auto_20181128_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='item_external',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='jmeno',
            field=models.CharField(max_length=200, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tridni',
            field=models.CharField(max_length=200, verbose_name='Třída'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_link',
            field=models.CharField(max_length=500000),
        ),
    ]
