# Generated by Django 2.1.3 on 2018-12-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zsbila', '0006_auto_20181201_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tridni',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Třída'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autor'),
        ),
    ]
